version: "3"
services:
  app:
    container_name: api_gateway
    build: "."
    ports:
      - 5000:5000
    restart: always
    networks:
      - fiuber-network

networks:
  fiuber-network:
    driver: bridge
    name: fiuber-network
